Add some logic for handling aws docker repos.

diff --git a/potr b/potr
--- a/potr
+++ b/potr
@@ -2,9 +2,13 @@
 
 # Simple script to run build commands in docker.
 
+version="latest"
+
 source potr.conf
 
 tempFileName="/tmp/potr.$$"
+
+aws='docker run --rm -t $(tty &>/dev/null && echo "-i") -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" -v "$(pwd):/project" mesosphere/aws-cli'
 
 run_print() {
     echo $1
@@ -126,6 +130,35 @@ then
     docker rm $name-build
     docker rm $name
     exit 0
+fi
+
+
+if [ $1 == "aws-docker-login" ]
+then
+    cmd="$aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION | tr -d '\r\n' | bash"
+    run_print 'bash -c "$cmd"'
+fi
+
+if [ $1 == "push" ]
+then
+    # Build the code
+    run_build
+    if [ $? -ne 0 ]
+    then
+        # If the build command failed, then exit
+        exit $?
+    fi
+
+    # Build the deploy container.
+    deploy_container
+    if [ $? -ne 0 ]
+    then
+        # If the build command failed, then exit
+        exit $?
+    fi
+
+    run_print "docker tag $did $docker_repo/$name:$version"
+    run_print "docker push $docker_repo/$name:$version"
 fi
 
 kube_cleanup() {
