Validate the files in the container, add an explicit lock file to avoid the conatiner image changing without our knowledge. Clean up commands.

diff --git a/potr b/potr
--- a/potr
+++ b/potr
@@ -4,9 +4,16 @@
 
 version="latest"
 
+if [ ! -f "potr.conf" ]
+then
+    echo "This directory doesn't appear to be a potr projectroot. No potr.conf file found."
+fi
+
 source potr.conf
 
 tempFileName="/tmp/potr.$$"
+hashDockerPath="/tmp/potr.hash.$$"
+lockFileName="potr.sum"
 
 aws='docker run --rm -t $(tty &>/dev/null && echo "-i") -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" -v "$(pwd):/project" mesosphere/aws-cli'
 
@@ -30,6 +37,52 @@ build_container() {
     # versions building on the same machine.
     id=`cat $tempFileName`
     rm $tempFileName
+
+    check_and_update_lock_file
+}
+
+check_and_update_lock_file() {
+    # Get a hash of the build container
+    mkdir -p $hashDockerPath
+    cat << EOF > $hashDockerPath/Dockerfile
+    FROM $id
+    FROM centos:7
+
+    COPY --from=0 / /to-hash
+    RUN tar --mtime='2019-01-01 00:00Z' --sort=name -cf /to-hash | md5sum > /build-container-hash.md5
+    CMD ["cat", "/build-container-hash.md5"]
+EOF
+
+    docker build -t $name-build-hash-$id $hashDockerPath
+
+    rm -rf $hashDockerPath
+
+    hash=`docker run --rm "$name-build-hash-$id"`
+
+    # If the lock file exists, check the id of the built container against it
+    if [ -f $lockFileName ]
+    then
+        lockedHash=`cat $lockFileName`
+        if [ "$hash" != "$lockedHash" ]
+        then
+            echo ""
+            echo "*****************************************************************"
+            echo "Locked container doesn't equal built container"
+            echo " Locked hash: $lockedHash"
+            echo " Built hash:  $hash"
+            echo ""
+            echo "If you have updated the build container definition run \"potr update\""
+            echo "to update the lock file. If not, you probably have a non-stable build"
+            echo "container, which you need to fix."
+            echo ""
+            echo ""
+
+            exit 1
+        fi
+    else
+        echo "Updating lock file."
+        echo "$hash" > $lockFileName
+    fi
 }
 
 deploy_container() {
@@ -84,23 +137,37 @@ fi
 
 if [ $1 == "help" ] || [ $1 == "-h" ] || [ $1 == "--help" ]
 then
-    echo "Potr is a simple container build script."
-    echo "it is meant only to perform common out of container"
-    echo "operations (build a build container, run it etc.)"
-    echo "Run with no arguments it will run the build container"
-    echo "without passing any arguments."
-    echo "commands:"
-    echo " run 'cmd' - run the given command inside a build container instance"
-    echo " drun 'cmd' - run the given command inside a deploy container."
-    echo " push - build the deployment container and push it to the repo noted in the potr.conf file"
+    cat << EOF
+
+Potr is a simple container build script. it is meant only to perform common out of container operations (build a build container, run it etc.) Run with no arguments it will run the build container without passing any arguments.
+
+Commands:
+
+    build [args]- run the build container, optionally providing extra commands (or arguments) to the build container.
+    deploy - run the build container and create a deploy container locally.
+    update - update the locked container definition.
+    clean - remove the build and deployment containers for this project.
+    drun 'cmd' - run the given command inside a deploy container.
+    push - build the deployment container and push it to the repo noted in the potr.conf file
+    deploy - build the deployment container and put it in the local docker images.
+
+EOF
+
     exit 0
 fi
 
-if [ $1 == "run" ]
+if [ $1 == "build" ]
 then
     shift
     run_build "$@"
     exit $?
+fi
+
+if [ $1 == "update" ]
+then
+    rm $lockFileName
+    build_container
+    exit 0
 fi
 
 if [ $1 == "drun" ]
@@ -127,30 +194,36 @@ fi
 
 if [ $1 == "clean" ]
 then
-    if [ -n "$output_dirs" ]
-    then
-        rm -rf $output_dirs
-    fi
+    docker rmi $name-build
+    docker rmi $name
+    hashImages=`docker images -q $name-build-hash-*`
+    docker rmi $hashImages
     exit 0
 fi
-
-if [ $1 == "veryclean" ]
-then
-    if [ -n "$output_dirs" ]
-    then
-        rm -rf $output_dirs
-        exit $?
-    fi
-    docker rm $name-build
-    docker rm $name
-    exit 0
-fi
-
 
 if [ $1 == "aws-docker-login" ]
 then
     cmd="$aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION | tr -d '\r\n' | bash"
     run_print 'bash -c "$cmd"'
+fi
+
+if [ $1 == "deploy" ]
+then
+    # Build the code
+    run_build
+    if [ $? -ne 0 ]
+    then
+        # If the build command failed, then exit
+        exit $?
+    fi
+
+    # Build the deploy container.
+    deploy_container
+    if [ $? -ne 0 ]
+    then
+        # If the build command failed, then exit
+        exit $?
+    fi
 fi
 
 if [ $1 == "push" ]
@@ -173,44 +246,4 @@ then
 
     run_print "docker tag $did $docker_repo/$name:$version"
     run_print "docker push $docker_repo/$name:$version"
-fi
-
-kube_cleanup() {
-    # Tear things down
-    run_print "kubectl -f deploy/$name-test delete"
-}
-
-if [ $1 == "kube" ]
-then
-    # Build the code
-    run_build
-    if [ $? -ne 0 ]
-    then
-        # If the build command failed, then exit
-        exit $?
-    fi
-
-    # Build the deploy container.
-    deploy_container
-    if [ $? -ne 0 ]
-    then
-        # If the build command failed, then exit
-        exit $?
-    fi
-
-    trap kube_cleanup 2
-
-    # Deploy the app as a compact deployment
-    run_print "kubectl -f deploy/$name-test create"
-
-    # Tail the logs
-    stern $name*
-
-    kube_cleanup
-fi
-
-if [ $1 == "secret" ]
-then
-    kubectl delete secret $name-creds
-    kubectl create secret generic $name-creds --from-file $HOME/.credentials
 fi
